=== robotic-biology/pm-project-annotator/data/project.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="JobProtocolEditorSaveData" type="JobProtocolEditorSaveDataType"/>
  <xs:complexType name="settingParam1Type">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="itemType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="xs:string" name="itemId" maxOccurs="1" minOccurs="1"/>
      <xs:element name="type" maxOccurs="1" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="id" maxOccurs="1" minOccurs="1"/>
      <xs:element name="linkLineNo">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
      <xs:element name="linkItemNo">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
      <xs:element type="objectTypeType" name="objectType"/>
      <xs:element type="xs:string" name="commandType"/>
      <xs:element name="category">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
      <xs:element type="settingParam1Type" name="settingParam1"/>
      <xs:element type="settingParam2Type" name="settingParam2"/>
      <xs:element type="settingParam3Type" name="settingParam3"/>
      <xs:element type="settingParam4Type" name="settingParam4"/>
      <xs:element type="xs:string" name="settingParam4Sub"/>
      <xs:element name="settingParam2Sub">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
      <xs:element name="settingParam3Sub">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
      <xs:element name="settingParam1Sub">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="statusType">
    <xs:sequence>
      <xs:element type="xs:string" name="useAdjustTopPosision"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="settingParam2Type">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="settingParam4Type">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="settingParam3Type">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="headerType">
    <xs:sequence>
      <xs:element type="xs:string" name="dataVersion"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="objectTypeType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="mainType">
    <xs:sequence>
      <xs:element name="protocolMetaData" type="protocolMetaDataType" maxOccurs="1" minOccurs="0"></xs:element>
      <xs:element type="objectType" name="object"
                  maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="JobProtocolEditorSaveDataType">
    <xs:sequence>
      <xs:element type="headerType" name="header"/>
      <xs:element type="statusType" name="status"/>
      <xs:element type="mainType" name="main" maxOccurs="1" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="objectType">
    <xs:sequence>
      <xs:element name="objectId" maxOccurs="1" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:element>
      <xs:element type="itemType" name="item" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="protocolMetaDataType">
    <xs:sequence>
      <xs:element name="title" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
      <xs:element name="modules" type="modulesType" maxOccurs="1" minOccurs="0"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="modulesType">
    <xs:sequence>
      <xs:element name="module" type="moduleType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="moduleType">
    <xs:sequence>
      <xs:element name="name" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
      <xs:element name="startObjectId" type="xs:int" maxOccurs="1"
                  minOccurs="1">
      </xs:element>
      <xs:element name="startItemId" type="xs:int" maxOccurs="1"
                  minOccurs="1">
      </xs:element>
      <xs:element name="endObjectId" type="xs:int" maxOccurs="1"
                  minOccurs="1">
      </xs:element>
      <xs:element name="endItemId" type="xs:int" maxOccurs="1"
                  minOccurs="1">
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== robotic-biology/pm-project-annotator/data/protocol_with_metadata.xml
<JobProtocolEditorSaveData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="project.xsd">
    <header>
        <dataVersion>1.1.0.0</dataVersion>
    </header>
    <status>
        <useAdjustTopPosision>0</useAdjustTopPosision>
    </status>
    <main>
        <protocolMetaData>
            <title>Exp_Chromatin IP</title>
            <modules>
                <module>
                    <name>PCR</name>
                    <startObjectId>1</startObjectId>
                    <startItemId>1</startItemId>
                    <endObjectId>3</endObjectId>
                    <endItemId>10</endItemId>
                </module>
                <module>
                    <name>module2</name>
                    <startObjectId>3</startObjectId>
                    <startItemId>11</startItemId>
                    <endObjectId>4</endObjectId>
                    <endItemId>12</endItemId>
                </module>
            </modules>
        </protocolMetaData>
        <object>
            <objectId>1</objectId>
            <item>
                <itemId>1</itemId>
                <type>OBJECT_START</type>
                <id>0</id>
                <linkLineNo>1</linkLineNo>
                <linkItemNo>15</linkItemNo>
                <objectType name="Dish 100">OBJ401</objectType>
                <settingParam1 name="Title">Chromatin IP</settingParam1>
                <settingParam2 name="Device">CO2 Incubator</settingParam2>
                <settingParam3 name="No. of objects">1</settingParam3>
                <settingParam4 name="Initial volume">0</settingParam4>
                <settingParam4Sub>[&#65397;L]</settingParam4Sub>
            </item>
            <item>
                <itemId>2</itemId>
                <type>COMMAND_DISCARD</type>
                <id>63</id>
                <commandType>COM_DISCARD_00_0013</commandType>
                <category>DISCARD</category>
                <settingParam1 name="Collect">Supernatant</settingParam1>
                <settingParam2 name="Rack">--</settingParam2>
            </item>
            <item>
                <itemId>3</itemId>
                <type>COMMAND_ADD</type>
                <id>13</id>
                <commandType>COM_ADD_00_0013</commandType>
                <category>ADD</category>
                <settingParam1 name="Reagent">Wash Liquid</settingParam1>
                <settingParam2 name="Reagent quantity">5</settingParam2>
                <settingParam2Sub>[mL]</settingParam2Sub>
            </item>
            <item>
                <itemId>4</itemId>
                <type>COMMAND</type>
                <id>32</id>
                <commandType>COM_MIX_00_0013</commandType>
                <category>MIX</category>
                <settingParam1 name="Device">Etc.</settingParam1>
                <settingParam2 name="Temperature">25</settingParam2>
                <settingParam2Sub>[&#65392;C]</settingParam2Sub>
                <settingParam3 name="Timer">5</settingParam3>
                <settingParam3Sub>[sec]</settingParam3Sub>
            </item>
            <item>
                <itemId>5</itemId>
                <type>COMMAND_DISCARD</type>
                <id>63</id>
                <commandType>COM_DISCARD_00_0013</commandType>
                <category>DISCARD</category>
                <settingParam1 name="Collect">Supernatant</settingParam1>
                <settingParam2 name="Rack">--</settingParam2>
            </item>
            <item>
                <itemId>6</itemId>
                <type>COMMAND_ADD</type>
                <id>13</id>
                <commandType>COM_ADD_00_0013</commandType>
                <category>ADD</category>
                <settingParam1 name="Reagent">Reagent A</settingParam1>
                <settingParam2 name="Reagent quantity">5</settingParam2>
                <settingParam2Sub>[mL]</settingParam2Sub>
            </item>
            <item>
                <itemId>7</itemId>
                <type>COMMAND</type>
                <id>32</id>
                <commandType>COM_MIX_00_0013</commandType>
                <category>MIX</category>
                <settingParam1 name="Device">Etc.</settingParam1>
                <settingParam2 name="Temperature">25</settingParam2>
                <settingParam2Sub>[&#65392;C]</settingParam2Sub>
                <settingParam3 name="Timer">5</settingParam3>
                <settingParam3Sub>[sec]</settingParam3Sub>
            </item>
            <item>
                <itemId>8</itemId>
                <type>COMMAND</type>
                <id>82</id>
                <commandType>COM_REACT_00_0013</commandType>
                <category>REACT</category>
                <settingParam1 name="Situation">RT</settingParam1>
                <settingParam2 name="Timer">10</settingParam2>
                <settingParam2Sub>[min]</settingParam2Sub>
            </item>
            <item>
                <itemId>9</itemId>
                <type>COMMAND_ADD</type>
                <id>13</id>
                <commandType>COM_ADD_00_0013</commandType>
                <category>ADD</category>
                <settingParam1 name="Reagent">Reagent B</settingParam1>
                <settingParam2 name="Reagent quantity">200</settingParam2>
                <settingParam2Sub>[&#65397;L]</settingParam2Sub>
            </item>
            <item>
                <itemId>10</itemId>
                <type>COMMAND</type>
                <id>32</id>
                <commandType>COM_MIX_00_0013</commandType>
                <category>MIX</category>
                <settingParam1 name="Device">Etc.</settingParam1>
                <settingParam2 name="Temperature">25</settingParam2>
                <settingParam2Sub>[&#65392;C]</settingParam2Sub>
                <settingParam3 name="Timer">5</settingParam3>
                <settingParam3Sub>[sec]</settingParam3Sub>
            </item>
            <item>
                <itemId>11</itemId>
                <type>COMMAND</type>
                <id>82</id>
                <commandType>COM_REACT_00_0013</commandType>
                <category>REACT</category>
                <settingParam1 name="Situation">RT</settingParam1>
                <settingParam2 name="Timer">5</settingParam2>
                <settingParam2Sub>[min]</settingParam2Sub>
            </item>
            <item>
                <itemId>12</itemId>
                <type>COMMAND_DISCARD</type>
                <id>63</id>
                <commandType>COM_DISCARD_00_0013</commandType>
                <category>DISCARD</category>
                <settingParam1 name="Collect">Supernatant</settingParam1>
                <settingParam2 name="Rack">--</settingParam2>
            </item>
            <item>
                <itemId>13</itemId>
                <type>COMMAND_ADD</type>
                <id>13</id>
                <commandType>COM_ADD_00_0013</commandType>
                <category>ADD</category>
                <settingParam1 name="Reagent">Reagent for Collecting Cell</settingParam1>
                <settingParam2 name="Reagent quantity">1</settingParam2>
                <settingParam2Sub>[mL]</settingParam2Sub>
            </item>
            <item>
                <itemId>14</itemId>
                <type>COMMAND_TRANSFER</type>
                <id>101</id>
                <linkLineNo>2</linkLineNo>
                <linkItemNo>14</linkItemNo>
                <commandType>COM_SCRAPE_00_0013</commandType>
                <category>SCRAPE</category>
            </item>
            <item>
                <itemId>15</itemId>
                <type>OBJECT_END</type>
                <id>0</id>
                <linkLineNo>1</linkLineNo>
                <linkItemNo>1</linkItemNo>
                <objectType name="Dish 100">OBJ401</objectType>
                <settingParam1 name="Title">DustBox</settingParam1>
            </item>
        </object>
        <object>
            <objectId>2</objectId>
            <item>
                <itemId>1</itemId>
                <type>OBJECT_START</type>
                <id>0</id>
                <linkLineNo>2</linkLineNo>
                <linkItemNo>31</linkItemNo>
                <objectType name="Tube 1.5">OBJ103</objectType>
                <settingParam2 name="Device">RT</settingParam2>
                <settingParam3 name="No. of objects">1</settingParam3>
                <settingParam4 name="Initial volume">0</settingParam4>
                <settingParam4Sub>[&#65397;L]</settingParam4Sub>
            </item>
            <item>
                <itemId>2</itemId>
                <type>BLANK</type>
                <id>0</id>
            </item>
            <item>
                <itemId>3</itemId>
                <type>BLANK</type>
                <id>0</id>
            </item>
            <item>
                <itemId>4</itemId>
                <type>BLANK</type>
                <id>0</id>
            </item>
            <item>
                <itemId>5</itemId>
                <type>BLANK</type>
                <id>0</id>
            </item>
            <item>
                <itemId>6</itemId>
                <type>BLANK</type>
                <id>0</id>
            </item>
            <item>
                <itemId>7</itemId>
                <type>BLANK</type>
                <id>0</id>
            </item>
            <item>
                <itemId>8</itemId>
                <type>BLANK</type>
                <id>0</id>
            </item>
            <item>
                <itemId>9</itemId>
                <type>BLANK</type>
                <id>0</id>
            </item>
            <item>
                <itemId>10</itemId>
                <type>BLANK</type>
